### ISSUE TITLE
where to download paper？

### ISSUE THREAD

**Issue by zuowanbushiwo** [eran-shahar/Double-talk-Detection-aided-Residual-Echo-Suppression-via-Spectrogram-Masking-and-Refinement#1]
Hi @eran-shahar 
     No paper found via Google， and what is loss function？Can you upload the complete train code? 
Thanks！

**Comment by echocatzh** [comment]
I found the download link on [researchgate](https://www.researchgate.net/publication/362955799_Double-Talk_Detection-Aided_Residual_Echo_Suppression_via_Spectrogram_Masking_and_Refinement)

**Comment by zuowanbushiwo** [comment]
@echocatzh 
Thanks，Got it！
